/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebtsIndexRouteImport } from './routes/debts/index'

const DebtsIndexRoute = DebtsIndexRouteImport.update({
  id: '/debts/',
  path: '/debts/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/debts': typeof DebtsIndexRoute
}
export interface FileRoutesByTo {
  '/debts': typeof DebtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/debts/': typeof DebtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/debts'
  fileRoutesByTo: FileRoutesByTo
  to: '/debts'
  id: '__root__' | '/debts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DebtsIndexRoute: typeof DebtsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debts/': {
      id: '/debts/'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DebtsIndexRoute: DebtsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
